### ISSUE TITLE
Bad parsing

### ISSUE THREAD

**Issue by aaburlaka** [LucaDevelop/telegram-entities-decoder#1]
If I send
`<b>Start it!</b>  
Push the button`

your parser gives
`<b>Start it!  
</b>Push the button`

**Comment by LucaDevelop** [comment]
I can't replicate, if I send to the bot this:
<img width="278" alt="Schermata 2021-04-23 alle 23 41 51" src="https://user-images.githubusercontent.com/68305127/115932628-96aa0180-a48d-11eb-9b40-86446391c4c5.png">

the decode function returns:

`<b>Start it!</b> Push the button`

IMHO you selected the whitespace when you applied the style on the telegram client.
